# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 676ec2b930d24def4ff9b043dc7463756867629227408ca84a89a7f8222994a4cc1722813239e364a795278b187bff713b53ff3abeb558744e59c77ff1a55386

test:
  secret_key_base: 77444ca892ff4fc9597140d991bcf29d9aa061a4809de341454166fe9dfa8bfab29a0026c30ed6b15b402eb14ac37418bc7df02e16f566218e6f3fc25aad367d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
